### ISSUE TITLE
Everything scales down to aspect ratio except player portrait

### ISSUE THREAD

**Issue by Griffendahl** [Jademalo/SurroundFix#2]
Love the addon, works brilliant. However my player portrait remains in my upper left corner, way out of sight on my 32:9 screen.

**Comment by Jademalo** [comment]
Strange, are you using any other addons that affect the player portrait?
This shouldn't be an issue with the vanilla portrait.

**Comment by Griffendahl** [comment]
No, even with all other addons disabled this happens. But as far as I can see only on my warlock, all other characters are ok.


![surround](https://user-images.githubusercontent.com/49407664/112443173-eee5ca80-8d4c-11eb-8e07-0924f07873ea.png)

**Comment by Jademalo** [comment]
Hmm, that's extremely weird. Let me look into it quickly

**Comment by Jademalo** [comment]
Can you type `/fstack` and then take a screenshot hovering over the portrait?

**Comment by Jademalo** [comment]
Can you type `/fstack` and then take a screenshot hovering over the portrait?

![image](https://user-images.githubusercontent.com/386846/112444039-847d5c00-8d45-11eb-9b9c-9f06c0e79375.png)

Ideally try to press alt so the arrow in the box is next to `PlayerFrame` so I can see the parent of it

**Comment by Jademalo** [comment]
`/run PlayerFrame:SetParent(UIParent)`

Also let me know if this fixes it

**Comment by Griffendahl** [comment]
The command changes nothing as far as I can see.

![fstack1](https://user-images.githubusercontent.com/49407664/112445952-fce91a80-8d4f-11eb-8819-7fdd49dc6d6f.png)

![fstack2](https://user-images.githubusercontent.com/49407664/112446355-66692900-8d50-11eb-9cbc-0e6da5f2e77c.png)

**Comment by Jademalo** [comment]
When you're hovering over the player frame like in the second image, press alt a few times. It should change which frame the arrow in the box is pointing to.

![image](https://user-images.githubusercontent.com/386846/112448155-053e5700-8d4a-11eb-963f-05fac0268cbf.png)

Try to get one where the arrow is pointing to just `PlayerFrame` like in this image

**Comment by Griffendahl** [comment]
Like so?

![afbeelding](https://user-images.githubusercontent.com/49407664/112461520-480b2980-8d60-11eb-939d-bfa8a5d0e868.png)

**Comment by Jademalo** [comment]
Yes, that's perfect.
Right, so it was what I suspected, the player frame is for some reason not locked to UIParent.

Oh, I see what you've done. Right click the player frame, go down to "move" near the bottom, and click Reset Position.

![image](https://user-images.githubusercontent.com/386846/112467606-2d848080-8d5f-11eb-85ce-e89bb61db39e.png)

**Comment by Griffendahl** [comment]
Awesome, thanks for your great support. That was indeed the issue!
